version: "3.8"
services:

  goservices:
    build: "."
    container_name: goservices
    image: naufalhakm/library-api-author:v1
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: user
      DB_PASSWORD: password
      DB_DATABASE: library
    ports:
      - "8083:8083"  # REST API
    restart: always